    name: tudo
    description: tudo Webapp
    version: 0.0.1
    environment:
      sdk: '>=1.24.0 <2.0.0'
    dependencies:
      crypto: any
      angular: ^4.0.0
      angular_forms: ^1.0.0
      angular_router: ^1.0.2
      browser: ^0.10.0
      dart_to_js_script_rewriter: ^1.0.1
      cookie: "^0.0.4"
    transformers:
    - angular:
        entry_points: web/main.dart
    - dart_to_js_script_rewriter
    - $dart2js:
        commandLineOptions: [--show-package-warnings]